In [1]:
import pandas as pd

In [2]:
pd.__version__

'0.24.2'

In [2]:
import numpy as np

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
data['b']

0.5

In [58]:
pop_dic = {'Rajasthan': 68500000, 'Bihar': 240000000, 'MP': 20000000, 'UP': 150000000, 'Gujrat':50000000}

In [59]:
pop = pd.Series(pop_dic)
pop

Rajasthan     68500000
Bihar        240000000
MP            20000000
UP           150000000
Gujrat        50000000
dtype: int64

In [14]:
pop['Rajasthan']

68500000

In [15]:
pop['Rajasthan':'UP']

Rajasthan     68500000
Bihar        240000000
MP            20000000
UP           150000000
dtype: int64

In [16]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [17]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [20]:
pd.Series({2:'a',1:'b',3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [60]:
area_pop = {'Rajasthan': 432322, 'Bihar': 232342, 'MP': 4323232, 'UP': 324133, 'Gujrat': 23423}

In [61]:
area = pd.Series(area_pop)

In [7]:
area

Rajasthan     432322
Bihar         232342
MP           4323232
UP            324133
Gujrat         23423
dtype: int64

In [8]:
states = pd.DataFrame({'population': pop, 'area': area })

In [9]:
states

population     area
Rajasthan    68500000   432322
Bihar       240000000   232342
MP           20000000  4323232
UP          150000000   324133
Gujrat       50000000    23423

In [10]:
states.index

Index(['Rajasthan', 'Bihar', 'MP', 'UP', 'Gujrat'], dtype='object')

In [11]:
states.columns

Index(['population', 'area'], dtype='object')

In [12]:
states['area']

Rajasthan     432322
Bihar         232342
MP           4323232
UP            324133
Gujrat         23423
Name: area, dtype: int64

In [14]:
pd.DataFrame(pop, columns=['population'])

population
Rajasthan    68500000
Bihar       240000000
MP           20000000
UP          150000000
Gujrat       50000000

In [17]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [18]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [19]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.735045  0.564127
b  0.464956  0.055439
c  0.682773  0.451683

In [21]:
a = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
a

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [22]:
pd.DataFrame(a)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [23]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [24]:
ind[1]

3

In [27]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [28]:
print(ind.shape, ind.size, ind.ndim, ind.dtype)

(5,) 5 1 int64


In [31]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [32]:
inda = pd.Index([1,3,5,7,9])
indb = pd.Index([2,3,5,7,11])

In [33]:
inda & indb

Int64Index([3, 5, 7], dtype='int64')

In [35]:
inda | indb

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [36]:
inda ^ indb

Int64Index([1, 2, 9, 11], dtype='int64')

In [37]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
data['b']

0.5

In [40]:
'a' in data

True

In [41]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [43]:
data['e'] = 1.25

In [44]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [45]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [47]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [48]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [50]:
data = pd.Series(['a','b','c'], index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [51]:
data[1]

'a'

In [52]:
data[1:3]

3    b
5    c
dtype: object

In [54]:
data.loc[1]

'a'

In [55]:
data.loc[1:3]

1    a
3    b
dtype: object

In [56]:
data.iloc[1]

'b'

In [57]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [62]:
data = pd.DataFrame({'area': area, 'pop': pop})

In [63]:
data

area        pop
Rajasthan   432322   68500000
Bihar       232342  240000000
MP         4323232   20000000
UP          324133  150000000
Gujrat       23423   50000000

In [64]:
data.area is data['area']

True

In [65]:
data.pop is data['pop']

False

In [66]:
data.pop

<bound method NDFrame.pop of               area        pop
Rajasthan   432322   68500000
Bihar       232342  240000000
MP         4323232   20000000
UP          324133  150000000
Gujrat       23423   50000000>

In [67]:
data['pop']

Rajasthan     68500000
Bihar        240000000
MP            20000000
UP           150000000
Gujrat        50000000
Name: pop, dtype: int64

In [68]:
data['dencity'] = data['pop'] / data['area']
data

area        pop      dencity
Rajasthan   432322   68500000   158.446713
Bihar       232342  240000000  1032.960033
MP         4323232   20000000     4.626169
UP          324133  150000000   462.772998
Gujrat       23423   50000000  2134.653973

In [69]:
data.values

array([[4.32322000e+05, 6.85000000e+07, 1.58446713e+02],
       [2.32342000e+05, 2.40000000e+08, 1.03296003e+03],
       [4.32323200e+06, 2.00000000e+07, 4.62616857e+00],
       [3.24133000e+05, 1.50000000e+08, 4.62772998e+02],
       [2.34230000e+04, 5.00000000e+07, 2.13465397e+03]])

In [70]:
data.T

Rajasthan         Bihar            MP            UP        Gujrat
area     4.323220e+05  2.323420e+05  4.323232e+06  3.241330e+05  2.342300e+04
pop      6.850000e+07  2.400000e+08  2.000000e+07  1.500000e+08  5.000000e+07
dencity  1.584467e+02  1.032960e+03  4.626169e+00  4.627730e+02  2.134654e+03

In [71]:
data.values[0]

array([4.32322000e+05, 6.85000000e+07, 1.58446713e+02])

In [72]:
data['area']

Rajasthan     432322
Bihar         232342
MP           4323232
UP            324133
Gujrat         23423
Name: area, dtype: int64

In [73]:
data.iloc[:3, :2]

area        pop
Rajasthan   432322   68500000
Bihar       232342  240000000
MP         4323232   20000000

In [74]:
data.loc[:'UP', :'pop']

area        pop
Rajasthan   432322   68500000
Bihar       232342  240000000
MP         4323232   20000000
UP          324133  150000000

In [77]:
data.ix[:3, :'dencity']

C:\Users\Bhavesh kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area        pop      dencity
Rajasthan   432322   68500000   158.446713
Bihar       232342  240000000  1032.960033
MP         4323232   20000000     4.626169

In [78]:
data.loc[data.dencity > 100, ['pop','dencity']]

pop      dencity
Rajasthan   68500000   158.446713
Bihar      240000000  1032.960033
UP         150000000   462.772998
Gujrat      50000000  2134.653973

In [79]:
data.iloc[0, 2] = 90
data

area        pop      dencity
Rajasthan   432322   68500000    90.000000
Bihar       232342  240000000  1032.960033
MP         4323232   20000000     4.626169
UP          324133  150000000   462.772998
Gujrat       23423   50000000  2134.653973

In [80]:
data['MP':'UP']

area        pop     dencity
MP  4323232   20000000    4.626169
UP   324133  150000000  462.772998

In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [3]:
rng

In [4]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A','B','C','D'])

In [5]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [8]:
area = pd.Series({'Alaska':1723337, 'Texas': 695662, 'California':423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas':26448133, 'New York': 19651127}, name='population')

In [9]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018654
dtype: float64

In [10]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [11]:
A = pd.Series([2,4,6], index=[0, 1, 2])
B = pd.Series([1,3,5], index=[1 ,2 ,3])

In [12]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [13]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [14]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns = list('AB'))

In [15]:
A

A   B
0  1  11
1  5   1

In [16]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [17]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [19]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [20]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [21]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [22]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [23]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [25]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [26]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

In [2]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [3]:
for dtype in ['object', 'int']:
    print("dtype = ", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype =  object
140 ms ± 22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype =  int
6.09 ms ± 88.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [4]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [5]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [6]:
vals2

array([ 1., nan,  3.,  4.])

In [7]:
1 + np.nan

nan

In [8]:
0 * np.nan

nan

In [9]:
vals2.sum(), vals2.max(), vals2.min()

(nan, nan, nan)

In [10]:
np.nansum(vals2), np.nanmax(vals2), np.nanmin(vals2)

(8.0, 4.0, 1.0)

In [11]:
pd.Series([1, np.nan, 3, None])

0    1.0
1    NaN
2    3.0
3    NaN
dtype: float64

In [12]:
x = pd.Series(range(2), dtype=int)

In [13]:
x

0    0
1    1
dtype: int32

In [14]:
x[0] = None

In [15]:
x

0    NaN
1    1.0
dtype: float64

In [5]:
data = pd.Series([1, np.nan, 'hello', None])

In [7]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [8]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [9]:
data.dropna()

0        1
2    hello
dtype: object

In [12]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2,     3,    5],
                  [np.nan, 4,    6]])

In [13]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [14]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [16]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [17]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [20]:
 df.dropna(axis=1, how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [23]:
df.dropna(axis=0, thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [25]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [28]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [30]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [31]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [32]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [33]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [7]:
index = [('California', 2000), ('California', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]

In [8]:
population =  [33871648, 37253956,
             18976457, 19378102,
             20851820, 25145561]

In [9]:
pop = pd.Series(population, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [11]:
pop[('California', 2010): ('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [12]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [13]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [14]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [47]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [48]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [50]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [51]:
pop_df = pd.DataFrame({'total': pop, 'under18': [9267089, 9284094,
                                                 4687374, 4318033,
                                                 5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [52]:
fu18 = pop_df['under18'] / pop_df['total']
fu18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [53]:
fu18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [2]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.rand(4, 2), 
                  index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                 columns = ['data1', 'data2'])
df

data1     data2
a 1  0.912970  0.704826
  2  0.250499  0.998712
b 1  0.264705  0.344784
  2  0.234614  0.447531

In [9]:
data = {('California', 2000): 33871648,
         ('California', 2010): 37253956,
         ('Texas', 2000): 20851820,
         ('Texas', 2010): 25145561,
         ('New York', 2000): 18976457,
         ('New York', 2010): 19378102}
pop = pd.Series(data)

In [4]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [5]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [7]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [8]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])


MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [11]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [24]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names=['Year', 'Visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names=['Subject', 'Type'])

In [25]:
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

In [26]:
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

Subject      Bob       Guido         Sue      
Type          HR  Temp    HR  Temp    HR  Temp
Year Visit                                    
2013 1      34.0  37.5  24.0  38.1  31.0  35.9
     2      27.0  37.2  31.0  36.9  48.0  37.2
2014 1      59.0  36.2  23.0  35.8  47.0  36.4
     2      30.0  36.6  45.0  38.2  20.0  36.3

In [27]:
health_data['Guido']

Type          HR  Temp
Year Visit            
2013 1      48.0  36.1
     2      38.0  35.2
2014 1      29.0  36.4
     2      33.0  38.5

In [38]:
pop

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [39]:
pop['California', 2000]

33871648

In [40]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [55]:
pop.loc['California':'New York']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [56]:
pop[:, 2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [57]:
pop[pop > 22000000]

California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [58]:
pop[['California', 'Texas']]

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [69]:
health_data

Subject      Bob       Guido         Sue      
Type          HR  Temp    HR  Temp    HR  Temp
Year Visit                                    
2013 1      49.0  36.4  48.0  36.1  40.0  36.1
     2      47.0  38.2  38.0  35.2  25.0  35.8
2014 1      36.0  37.3  29.0  36.4  39.0  35.4
     2      40.0  37.0  33.0  38.5  28.0  36.6

In [60]:
health_data['Guido', 'HR']

Year  Visit
2013  1        48.0
      2        38.0
2014  1        29.0
      2        33.0
Name: (Guido, HR), dtype: float64

In [65]:
health_data.iloc[:2, :2]

Subject      Bob      
Type          HR  Temp
Year Visit            
2013 1      49.0  36.4
     2      47.0  38.2

In [66]:
health_data.loc[:, ('Bob', 'HR')]

Year  Visit
2013  1        49.0
      2        47.0
2014  1        36.0
      2        40.0
Name: (Bob, HR), dtype: float64

In [67]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-67-fb34fa30ac09>, line 1)

In [71]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

Subject      Bob Guido   Sue
Type          HR    HR    HR
Year Visit                  
2013 1      49.0  48.0  40.0
2014 1      36.0  29.0  39.0

In [3]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index = index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.012521
      2      0.850286
c     1      0.418408
      2      0.341868
b     1      0.558177
      2      0.512423
dtype: float64

In [4]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [5]:
data = data.sort_index()
data

char  int
a     1      0.012521
      2      0.850286
b     1      0.558177
      2      0.512423
c     1      0.418408
      2      0.341868
dtype: float64

In [6]:
data['a':'b']

char  int
a     1      0.012521
      2      0.850286
b     1      0.558177
      2      0.512423
dtype: float64

In [15]:
pop.unstack(level=0)

California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [16]:
pop.unstack(level=1)

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [17]:
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [19]:
pop_flat = pop.reset_index(name='population')
pop_flat

level_0  level_1  population
0  California     2000    33871648
1  California     2010    37253956
2    New York     2000    18976457
3    New York     2010    19378102
4       Texas     2000    20851820
5       Texas     2010    25145561

In [21]:
pop_flat.set_index(['level_0', 'level_1'])

population
level_0    level_1            
California 2000       33871648
           2010       37253956
New York   2000       18976457
           2010       19378102
Texas      2000       20851820
           2010       25145561

In [23]:
pop_fla

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [27]:
health_data

Subject      Bob       Guido         Sue      
Type          HR  Temp    HR  Temp    HR  Temp
Year Visit                                    
2013 1      34.0  37.5  24.0  38.1  31.0  35.9
     2      27.0  37.2  31.0  36.9  48.0  37.2
2014 1      59.0  36.2  23.0  35.8  47.0  36.4
     2      30.0  36.6  45.0  38.2  20.0  36.3

In [29]:
data_mean = health_data.mean(level='Year')
data_mean

Subject   Bob        Guido         Sue       
Type       HR   Temp    HR  Temp    HR   Temp
Year                                         
2013     30.5  37.35  27.5  37.5  39.5  36.55
2014     44.5  36.40  34.0  37.0  33.5  36.35

In [31]:
data_mean.mean(axis=1, level='Type')

Type         HR       Temp
Year                      
2013  32.500000  37.133333
2014  37.333333  36.583333

In [32]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [33]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x = [[1,2],
    [3,4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])